# Generated by Django 6.0.4 on 2026-05-03 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст запитання')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковий номер')),
            ],
            options={
                'verbose_name': 'Запитання',
                'verbose_name_plural': 'Запитання',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(verbose_name='Загальний бал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проходження')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Результат тесту',
                'verbose_name_plural': 'Результати тестів',
                'ordering': ['-created_at'],
            },
        ),
    ]
