# Generated by Django 6.0.4 on 2026-05-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва тесту')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='Коротка назва (для URL)')),
                ('description', models.TextField(blank=True, verbose_name='Опис тесту')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment', verbose_name='Тест'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment', verbose_name='Тест'),
            preserve_default=False,
        ),
    ]
