# Generated by Django 6.0.4 on 2026-05-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_question_assessment_testresult_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='about_text',
            field=models.TextField(blank=True, verbose_name='Детальний опис (HTML)'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість питань'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reliability',
            field=models.CharField(blank=True, max_length=100, verbose_name='Надійність'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='time_to_complete',
            field=models.CharField(blank=True, max_length=50, verbose_name='Час проходження'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис тесту (для списку)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='short_name',
            field=models.SlugField(unique=True, verbose_name='Коротка назва (для URL)'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Кількість балів (0, 1, 2...)')),
                ('text', models.CharField(max_length=200, verbose_name='Текст відповіді')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.assessment', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Варіант відповіді',
                'verbose_name_plural': 'Варіанти відповідей',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='ResultInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField(verbose_name='Мінімальний бал')),
                ('max_score', models.PositiveIntegerField(verbose_name='Максимальний бал')),
                ('result_title', models.CharField(max_length=200, verbose_name='Заголовок результату')),
                ('result_text', models.TextField(verbose_name='Текст результату')),
                ('recommendation', models.TextField(verbose_name='Рекомендація')),
                ('is_high_risk', models.BooleanField(default=False, verbose_name='Високий ризик (червона іконка)')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='assessments.assessment', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Інтерпретація результату',
                'verbose_name_plural': 'Інтерпретації результатів',
                'ordering': ['min_score'],
            },
        ),
    ]
