# Generated by Django 6.0.4 on 2026-05-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_about_text_assessment_questions_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='instruction',
            field=models.TextField(blank=True, verbose_name='Інструкція перед проходженням'),
        ),
    ]
