# Generated by Django 6.0.4 on 2026-05-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='icon',
            field=models.CharField(default='assessments/images/anxiety.png', help_text='assessments/images/depressed.png', max_length=100, verbose_name='Шлях до іконки'),
        ),
    ]
