# Generated by Django 6.0.4 on 2026-05-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessment_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='assessment',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question', verbose_name='Запитання'),
            preserve_default=False,
        ),
    ]
