# Generated by Django 6.0.4 on 2026-05-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_remove_choice_assessment_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scale',
            field=models.CharField(blank=True, max_length=50, verbose_name='Шкала/Субшкала'),
        ),
        migrations.AddField(
            model_name='resultinterpretation',
            name='scale',
            field=models.CharField(blank=True, max_length=50, verbose_name='Шкала'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='scale_scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='Бали по шкалах'),
        ),
    ]
