# Generated by Django 6.0.4 on 2026-05-07 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReactionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PHYSICAL', 'Physical Reactions'), ('EMOTIONAL', 'Emotional Reactions'), ('THINKING', 'Thinking Reactions'), ('ACTION', 'Action Reactions')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_trigger', models.CharField(blank=True, help_text='Якщо користувач ввів свій варіант', max_length=255)),
                ('distress_level', models.PositiveIntegerField(default=0)),
                ('custom_context', models.CharField(blank=True, max_length=255)),
                ('contexts', models.ManyToManyField(blank=True, to='tools.contextoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('IMMEDIATE', 'Immediate (First few minutes)'), ('SHORT_TERM', 'Short-Term (15 mins to few hours)'), ('LONG_TERM', 'Long-Term (Hours to days)')], max_length=15)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.reactionoption')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='tools.triggerlog')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='triggerlog',
            name='triggers',
            field=models.ManyToManyField(blank=True, to='tools.triggeroption'),
        ),
    ]
